.TH facial_test 1 "November 2025" "pam_facial_auth" "User Commands"
.SH NAME
facial_test \- testa un modello di riconoscimento facciale

.SH SYNOPSIS
.B facial_test
\-u USER
[\-m MODEL] [\-c CONFIG] [\-d DEVICE]
[\-\-threshold VALUE] [\-v] [\-\-nogui]

.SH DESCRIPTION
Il comando
.B facial_test
esegue un tentativo di riconoscimento facciale usando webcam e un modello
XML precedentemente addestrato.

Per impostazione predefinita il modello è cercato in:
.nf
    /etc/pam_facial_auth/models/USER.xml
.fi

.SH OPTIONS
.TP
.B \-u, \-\-user USER
Utente da verificare (obbligatorio).

.TP
.B \-m, \-\-model FILE
File modello XML (opzionale).

.TP
.B \-c, \-\-config FILE
File di configurazione (default: /etc/security/pam_facial.conf)

.TP
.B \-d, \-\-device DEV
Webcam da usare.

.TP
.B \-\-threshold VALUE
Override della soglia di accettazione.

.TP
.B \-v, \-\-verbose
Output dettagliato.

.TP
.B \-\-nogui
Disabilita eventuali finestre GUI.

.SH EXIT STATUS
0  Successo
2  Fallimento autenticazione
1  Errore

.SH SEE ALSO
facial_training(1), facial_capture(1), pam_facial_auth(8)
