.TH facial_capture 1 "November 2025" "pam_facial_auth 1.0" "User Commands"
.SH NAME
facial_capture \- capture face images for training facial recognition models
.SH SYNOPSIS
.B facial_capture
\-u USER
[\-d DEVICE] [\-w WIDTH] [\-h HEIGHT] [\-n FRAMES]
[\-s MS] [\-f] [\-\-clean] [\-\-reset]
[\-g] [\-v] [\-c FILE] [\-\-format EXT]
.SH DESCRIPTION
The
.B facial_capture
utility captures face images from a video device and stores them in the
user-specific image directory. These images are used by
.BR facial_training (1)
to generate facial recognition models.

Images are processed through a Haar cascade classifier for face detection
and are stored as grayscale, equalized, and normalized frames.

.SH OPTIONS
.TP
.BR \-u " " USER ", " \-\-user=USER
Specify the user for whom images will be captured.
.TP
.BR \-d " " DEVICE ", " \-\-device=DEVICE
Override the video capture device (default: /dev/video0).
.TP
.BR \-w " " WIDTH ", " \-\-width=WIDTH
Set capture frame width.
.TP
.BR \-h " " HEIGHT ", " \-\-height=HEIGHT
Set capture frame height.
.TP
.BR \-n " " FRAMES ", " \-\-frames=FRAMES
Number of face images to capture.
.TP
.BR \-s " " MS ", " \-\-sleep=MS
Delay in milliseconds between captures.
.TP
.BR \-f ", " \-\-force
Force overwrite of existing images.
.TP
.BR \-g ", " \-\-nogui
Disable any graphical output.
.TP
.BR \-\-clean
Remove all images for the specified user.
.TP
.BR \-\-reset
Remove the user model and all images.
.TP
.BR \-v ", " \-\-debug
Enable verbose/debug mode.
.TP
.BR \-c " " FILE ", " \-\-config=FILE
Use an alternate configuration file.
.TP
.BR \-\-format " " EXT
Set the output image format (jpg, png, etc.).
.SH FILES
.TP
.I /etc/security/pam_facial.conf
Default configuration file.
.SH SEE ALSO
.BR facial_training (1),
.BR facial_test (1),
.BR pam_facial_auth (8)
.SH AUTHOR
Andrea Postiglione and contributors.
