.TH FACIAL_TRAINING 1 "2025-01" "pam_facial_auth" "User Commands"
.SH NAME
facial_training \- train the facial recognition model

.SH SYNOPSIS
.B facial_training
\-u USER
[\-i DIR] [\-o FILE]
[\-f] [\-v] [\-c FILE]

.SH DESCRIPTION
The
.B facial_training
tool loads previously captured face images for a user and trains an LBPH
(Local Binary Patterns Histograms) facial recognition model.

The resulting model is stored as an XML file under
.BR /etc/pam_facial_auth/models .

This model is used by the PAM module for authentication.

.SH OPTIONS
.TP
.B \-u, --user USER
User for which to train the model. Required.

.TP
.B \-i, --input DIR
Input directory containing training images
(default:
.BR /etc/pam_facial_auth/images/USER ).

.TP
.B \-o, --output FILE
Output model file
(default:
/etc/pam_facial_auth/models/USER.xml).

.TP
.B \-f, --force
Overwrite an existing model file.

.TP
.B \-v, --verbose
Enable verbose/debug logging.

.TP
.B \-c, --config FILE
Configuration file (default:
/etc/security/pam_facial.conf).

.TP
.B --help
Show usage and exit.

.SH FILES
.TP
.B /etc/pam_facial_auth/images/USER
Training image directory.
.TP
.B /etc/pam_facial_auth/models/USER.xml
Generated LBPH model.
.TP
.B /etc/security/pam_facial.conf
Global configuration.

.SH AUTHOR
Andrea Postiglione
