.TH facial_test 1 "November 2025" "pam_facial_auth 1.0" "User Commands"
.SH NAME
facial_test \- test a user's facial recognition model
.SH SYNOPSIS
.B facial_test
\-u USER
[\-m MODEL] [\-c FILE] [\-d DEVICE]
[\-\-threshold VALUE] [\-v] [\-\-nogui]
.SH DESCRIPTION
The
.B facial_test
tool authenticates a user against a trained facial recognition model by
capturing live frames from a video device and comparing them to the model.

This tool is intended for debugging and verification of recognition
accuracy outside the PAM authentication stack.

.SH OPTIONS
.TP
.BR \-u " " USER ", " \-\-user=USER
User to be authenticated.
.TP
.BR \-m " " MODEL ", " \-\-model=MODEL
Path to the model XML file. Defaults to basedir/models/<user>.xml.
.TP
.BR \-c " " FILE ", " \-\-config=FILE
Alternate configuration file.
.TP
.BR \-d " " DEVICE ", " \-\-device=DEVICE
Webcam device to use.
.TP
.BR \-\-threshold " " VALUE
Override recognition confidence threshold.
.TP
.BR \-v ", " \-\-verbose
Enable verbose output.
.TP
.BR \-\-nogui
Disable GUI features.
.SH SEE ALSO
.BR facial_capture (1),
.BR facial_training (1),
.BR pam_facial_auth (8)
.SH AUTHOR
Andrea Postiglione and contributors.
