.TH facial_training 1 "November 2025" "pam_facial_auth" "User Commands"
.SH NAME
facial_training \- addestra un modello biometrico del volto

.SH SYNOPSIS
.B facial_training
\-u USER \-m METHOD
[\-i DIR] [\-o FILE] [\-f] [\-v]

.SH DESCRIPTION
Il comando
.B facial_training
addestra un modello di riconoscimento facciale usando uno dei seguenti metodi:

.TP
.B lbph
Local Binary Pattern Histogram (robusto, raccomandato)

.TP
.B eigen
Eigenfaces (richiede molte immagini e un dataset omogeneo)

.TP
.B fisher
Fisherfaces (richiede dataset ben bilanciato)

Le immagini devono essere già presenti in:
.nf
    /etc/pam_facial_auth/images/USER/
.fi

Il modello risultante viene salvato in XML e sarà usato dal modulo PAM.

.SH OPTIONS
.TP
.B \-u, \-\-user USER
Utente (obbligatorio).

.TP
.B \-m, \-\-method {lbph,eigen,fisher}
Metodo di addestramento.

.TP
.B \-i, \-\-input DIR
Override di basedir per le immagini.

.TP
.B \-o, \-\-output FILE
Percorso completo per il modello XML.

.TP
.B \-f, \-\-force
Forza sovrascrittura modello.

.TP
.B \-v, \-\-verbose
Abilita debug.

.SH FILES
.nf
/etc/security/pam_facial.conf
/etc/pam_facial_auth/models/USER.xml
.fi

.SH SEE ALSO
facial_capture(1), facial_test(1), pam_facial_auth(8)
