.TH PAM_FACIAL_AUTH 8 "November 2025" "1.0" "PAM Module for Facial Authentication"
.SH NAME
pam_facial_auth \- Modulo PAM per il riconoscimento facciale
.SH SYNOPSIS
.B auth required pam_facial_auth.so [options]
.SH DESCRIPTION
Il modulo PAM `pam_facial_auth` fornisce il riconoscimento facciale come metodo di autenticazione. Utilizza un modello addestrato per verificare l'identità dell'utente basandosi sulle caratteristiche del volto. Il modulo può essere configurato per funzionare in modalità grafica o senza GUI.

Per impostazione predefinita, il modulo cercherà il modello facciale dell'utente nella directory:
