.TH PAM_FACIAL_AUTH 8 "November 2025" "pam_facial_auth" "PAM Modules"
.SH NAME
pam_facial_auth - Facial recognition authentication module for PAM
.SH SYNOPSIS
.PP
pam_facial_auth.so
.SH DESCRIPTION
The pam_facial_auth module is used for authenticating users using facial recognition.
It can be configured by editing the /etc/pam_facial_auth/pam_facial.conf file.
.SH CONFIGURATION
The configuration file defines the webcam device, image resolution, recognition threshold, etc.
.SH SEE ALSO
pam.conf(5), pam.d(5)

