# ================================
# pam_facial_auth configuration
# ================================

# Directory base (DEFAULT)
basedir=/etc/pam_facial_auth

# Camera configuration
device=
camera_index=0

frames=10
width=200
height=200
sleep_ms=150

threshold=60.0
debug=false
force_overwrite=false


# ================================
# DNN settings
# ================================

# Supported types:
#   caffe, tensorflow, onnx, openvino
dnn_type=onnx

# Tutti i path devono essere assoluti
dnn_model=
dnn_proto=

# cpu | opencl | cuda | openvino
dnn_device=cpu

# threshold logica per DNN [0-1]
dnn_threshold=0.6
